baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "EQ Codex"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

disqusShortname = "eqcodex"

[params]
  editURL = "https://github.com/eqcodex/eqcodex/edit/master/content/"
  description = "EQCodex"
  author = "Xackery X`Tal, Mathieu Cornic"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true
  themeVariant = "eqcodex"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "EQCodex"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/eqcodex/eqcodex"
weight = 10


[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
identifier = "ds"
url = "https://github.com/eqcodex/eqcodex"
weight = 10


[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Documentation Hugo"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Crédits"
url = "/credits"
weight = 30
