version: '3'
services:
  mariadb:
    image: "bitnami/mariadb:latest"
    volumes:
      - ./db:/bitnami/mariadb
      - ./backup:/backup
      - ./eqemu/bin/db:/eqemu/db
      - ./html:/html
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: eqemu
      MARIADB_USER: eqemu
      MARIADB_PASSWORD: eqemu
    ports:
      - "3306:3306"
    expose:
      - "3306"