.PHONY: build
build: 
	@(hugo -b https://eqcodex.com)
.PHONY: deploy
deploy: build
	@(firebase deploy)
.PHONY: scss
scss:
	@(docker run --rm -v $(PWD):$(PWD) -w $(PWD) node node scripts/font-generator/main.js)
	@(echo "/* This file is autogenerated via 'make scss'. DO NOT EDIT */" > static/css/xegony-awesome.css)
	@(docker run --rm -v $(PWD):$(PWD) -w $(PWD) jbergknoff/sass scss/app.scss >> static/css/xegony-awesome.css)
	@#(docker run --rm -v $(PWD)/font/xa:/data dockerfile/nodejs-bower-grunt grunt)
	
	#docker run --rm -v $(PWD):$(PWD) -w $(PWD) node npm install --save-dev webfont-webpack-plugin
	#docker run --rm -v $(PWD):$(PWD) -w $(PWD) node npm install --save-dev webfonts-generator
	