const webfontsGenerator = require('webfonts-generator');
const svgPath = 'svg/';
const fs = require('fs');

let dir = fs.readdirSync(svgPath);
dir = dir.filter( function(elm) {return elm.match(/.*\.(svg)/ig);});
let files = dir.map(el => 'svg/' + el);

webfontsGenerator({
  files: files,
  dest: 'static/fonts/',
  fontName: "eqcodex",
  writeFiles: true,
  templateOptions: {
      classPrefix: "xa-",
      baseSelector: ".xa"
  },
  cssFontsUrl: "/fonts",
  cssDest: "scss/xa.css"
  //cssDest: "../scss/eqcodex.css"
}, function(error) {
  if (error) {
    console.log('Fail!', error);
  } else {
    console.log('Done!');
  }
})


let iconFile = `
---
autogenerated: true
title: Icons
disableToc: true
---

### Icons

Here is a list of all xegony-awesome icons

Icon|Name|Code
---|---|---
`;

dir.forEach(ele => iconFile +=  '<i class="xa xa-'+ele.replace(".svg", "")+'"></i>|'+ele.replace(".svg", "")+'|xa xa-'+ele.replace(".svg", "")+'\n');
console.log(iconFile);
fs.writeFile("content/icons.md", iconFile, function(err) {
  if(err) {
      return console.log(err);
  }
  console.log("The file was saved!");
}); 